# Generated by Django 4.0.4 on 2022-06-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainIndex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pConsumptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.TimeField()),
                ('update_data', models.DateField()),
                ('grid_voltage', models.IntegerField(default=0)),
                ('pow_cnsmp_frm_grid', models.IntegerField(default=0)),
                ('solar_pv_voltage', models.IntegerField(default=0)),
                ('pow_cnsmp_frm_pv', models.IntegerField(default=0)),
                ('ev_batt_voltage', models.IntegerField(default=0)),
                ('ev_batt_power_cnsmp', models.IntegerField(default=0)),
            ],
        ),
    ]
